version: 2

jobs:
  test_node:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: yarn
      - run: yarn test.prod

  release:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn build.docs
      - run: yarn release
      - run: yarn release.docs

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node
      - release:
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - test_node
